name: zecure
description: A modern location app with map functionality

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  location: ^5.0.0
  http: ^1.2.0
  flutter_typeahead: ^5.0.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env