name: zecure
description: A modern location app with map functionality

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  location: ^5.0.0
  http: ^1.2.0
  flutter_typeahead: ^5.0.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.0
  supabase_flutter: ^2.1.0
  flutter_svg: ^2.0.7  # for logo
  intl: ^0.18.1  # for date formatting
  google_fonts: ^6.1.0  # for modern fonts
  share_plus: ^7.0.1
  image_picker: ^1.1.2
  flutter_datetime_picker: ^1.5.1
  provider: ^6.0.5
  google_maps_flutter: ^2.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/zecure.png
    - .env